apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo
  labels:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-demo
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kratix Nginx Promise</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .container { background: #f0f0f0; padding: 20px; border-radius: 5px; }
        h1 { color: #2c3e50; }
        .info { background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #3498db; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>🎉 Kratix Nginx Promise</h1>
        <div class="info">
          <p><strong>Deployment:</strong> nginx</p>
          <p><strong>Namespace:</strong> nginx-demo</p>
          <p><strong>Replicas:</strong> 3</p>
        </div>
        <div class="info">
          <p>This nginx was deployed using Kratix Promise patterns!</p>
          <p>The Promise framework allows you to define reusable application patterns.</p>
        </div>
      </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-demo
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 31080
    protocol: TCP
