kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-lab

nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - containerPort: 30080
      hostPort: 8080
      protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "app-purpose=apps"