apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    app-purpose: apps
spec:
  containers:
  - name: whoami
    image: traefik/whoami
    ports:
    - containerPort: 80
  nodeSelector:
    app-purpose: apps
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: NodePort
  selector:
    app-purpose: apps
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080